// Blog Storage - Uses API routes which are backed by Supabase

import type { Blog } from '@/types/blog';

// API response types
interface ApiResponse {
  success?: boolean;
  blogs?: Blog[];
  blog?: Blog;
  error?: string;
}

// Generate blog ID (UUID will be generated by Supabase, this is for fallback)
export function generateBlogId(): string {
  return `blog-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
}

// Generate URL slug from title
export function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// Calculate reading stats
export function calculateReadingStats(content: string): { wordCount: number; readingTime: number } {
  const plainText = content.replace(/<[^>]*>/g, '');
  const wordCount = plainText.trim().split(/\s+/).filter(Boolean).length;
  const readingTime = Math.max(1, Math.ceil(wordCount / 200));
  return { wordCount, readingTime };
}

// Fetch all blogs from API (Supabase)
export async function fetchBlogs(): Promise<Blog[]> {
  try {
    const response = await fetch('/api/blogs', { cache: 'no-store' });
    const data = await response.json() as ApiResponse;
    if (data.success && data.blogs) {
      return data.blogs;
    }
    return [];
  } catch (error) {
    console.error('Error fetching blogs:', error);
    return [];
  }
}

// Fetch single blog by ID or slug
export async function fetchBlog(idOrSlug: string): Promise<Blog | null> {
  try {
    const response = await fetch(`/api/blogs/${idOrSlug}`, { cache: 'no-store' });
    const data = await response.json() as ApiResponse;
    if (data.success && data.blog) {
      return data.blog;
    }
    return null;
  } catch (error) {
    console.error('Error fetching blog:', error);
    return null;
  }
}

// Create a new blog
export async function createBlog(blog: Omit<Blog, 'id' | 'createdAt' | 'updatedAt' | 'wordCount' | 'readingTime'>): Promise<Blog | null> {
  try {
    const response = await fetch('/api/blogs', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(blog),
    });
    const data = await response.json() as ApiResponse;
    if (data.success && data.blog) {
      return data.blog;
    }
    console.error('Create blog error:', data.error);
    return null;
  } catch (error) {
    console.error('Error creating blog:', error);
    return null;
  }
}

// Update a blog
export async function updateBlog(id: string, updates: Partial<Blog>): Promise<Blog | null> {
  try {
    const response = await fetch(`/api/blogs/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updates),
    });
    const data = await response.json() as ApiResponse;
    if (data.success && data.blog) {
      return data.blog;
    }
    console.error('Update blog error:', data.error);
    return null;
  } catch (error) {
    console.error('Error updating blog:', error);
    return null;
  }
}

// Delete a blog
export async function deleteBlog(id: string): Promise<boolean> {
  try {
    const response = await fetch(`/api/blogs/${id}`, {
      method: 'DELETE',
    });
    const data = await response.json() as ApiResponse;
    return data.success === true;
  } catch (error) {
    console.error('Error deleting blog:', error);
    return false;
  }
}

// ============================================
// Legacy functions for backwards compatibility
// These are kept to minimize changes to existing code
// ============================================

// Deprecated: Use fetchBlogs() instead
export async function initializeFromApi(): Promise<Blog[]> {
  return fetchBlogs();
}

// Deprecated: These localStorage functions now just delegate to API calls
// They're kept for backwards compatibility but should be migrated to async versions

export function getLocalBlogs(): Blog[] {
  // This is now a synchronous wrapper - returns empty array
  // Pages should use fetchBlogs() instead
  console.warn('getLocalBlogs() is deprecated. Use fetchBlogs() instead.');
  return [];
}

export function addLocalBlog(blog: Blog): void {
  // This is now a synchronous wrapper that starts an async operation
  console.warn('addLocalBlog() is deprecated. Use createBlog() instead.');
  void createBlog(blog);
}

export function updateLocalBlog(id: string, updates: Partial<Blog>): Blog | null {
  // This is now a synchronous wrapper - returns null
  console.warn('updateLocalBlog() is deprecated. Use updateBlog() instead.');
  void updateBlog(id, updates);
  return null;
}

export function deleteLocalBlog(id: string): boolean {
  // This is now a synchronous wrapper that starts an async operation
  console.warn('deleteLocalBlog() is deprecated. Use deleteBlog() instead.');
  void deleteBlog(id);
  return true;
}
